### ISSUE TITLE
get_sourceLink appears to need the same optional bindings as get_checksum

### ISSUE THREAD

**Issue by JeromySt** [microsoft/dia-rs#22]
Thank you for your help as I stumble through some fun projects using .pdb's.

I've come to ask for some assistance with [get_sourceLink](https://github.com/microsoft/dia-rs/blob/8f7353141af2bd2dcf073baff522ed230a29fa5b/src/bindings.rs#L12973).  Since this method also needs to be called twice, once to get the length to allocate, then again to get the contents I wanted to see if the same fix applied for get_checksum is applicable here.

The second question is that I just don't see which symbol to actually call get_sourceLink on.  My understanding was the sourceLink is an entire table of json formatted information and I could use a bit of hand-holding if you folks have the time on the proper way to invoke this to extract the information.

Thank you very much in advance.  This is the last piece of my PDB puzzle.

- Jeromy

**Comment by riverar** [comment]
> I wanted to see if the same fix applied for get_checksum is applicable here.

Yep, appears so!

> The second question is that I just don't see which symbol to actually call get_sourceLink on.

It's hanging off `IDiaSymbol10`, which you need to QI for.

Example:

```rust
// ...
let symbol: IDiaSymbol = symbols.Item(i as u32)?;
let symbol: IDiaSymbol10 = symbol.cast()?;
symbol.get_sourceLink(...)?;
```

**Comment by riverar** [comment]
Heads up, DIA SDK public API doesn't provide `IDiaSession13` and possibly other requisite types needed for a complete source link solution. You'll probably have to shell out to `C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv\pdbstr.exe` to retrieve that information.

Also be sure to upvote https://developercommunity.visualstudio.com/t/Is-there-an-API-for-reading-Source-Link-/1468642.

**Comment by JeromySt** [comment]
> Heads up, DIA SDK public API doesn't provide `IDiaSession13` and possibly other requisite types needed for a complete source link solution. You'll probably have to shell out to `C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv\pdbstr.exe` to retrieve that information.
> 
> Also be sure to upvote https://developercommunity.visualstudio.com/t/Is-there-an-API-for-reading-Source-Link-/1468642.

Would it be possible to expose these com api’s as well as a crate?
https://github.com/dotnet/symreader/blob/main/src/Microsoft.DiaSymReader/Reader/ISymUnmanagedReader4.cs

- Jeromy

**Comment by kennykerr** [comment]
This project is just a sample to show how such Rust bindings can be generated from metadata. Let's not feature creep this into something else. 😀 Our best bet is to get the DIA folks to update their SDK.
