### ISSUE TITLE
Wanted to get your input on IDiaSession::findFile(...)

### ISSUE THREAD

**Issue by JeromySt** [microsoft/dia-rs#24]
According to [IDiaSession::findFile(...)](https://learn.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/idiasession-findfile?view=vs-2022) the first parameter can be specified as null in order to search all files.

I'm trying to figure out how to pass in NULL for the IDiaSession in order to look up files that match a given regex and then enumerate the comperands which consume the file.  My guess is this is another metadata fix that will be needed in order to allow pcompiland to be null or not specified.

**Comment by riverar** [comment]
Likely another metadata bug, will patch that up when I get back to my PC!

**Comment by JeromySt** [comment]
Appreciate it.  I noticed the crate versions aren't incrementing.  Do these fixes overwrite the existing 0.10.0 crate or is there a process to publish the updated sources to crates.io?

**Comment by riverar** [comment]
I publish manually and on-demand. After we get this patched up I can publish. Alternatively, you can also just point to the repository as a dependency and run off the bleeding edge.

**Comment by riverar** [comment]
@JeromySt Actually, nothing to patch here this time. Kenny reminded me `IntoParam<Interface>` parameters are always optional. Peeking behind the curtain you'll find:

```rust
...
unsafe fn into_param(self) -> Param<T> {
    Param::Borrowed(match self {
        Some(item) => std::mem::transmute_copy(item),
        None => std::mem::zeroed(),
    })
}
...
```

So just pass in `None`, as such:

```rust
let files = session.findFile(None, PCWSTR::null(), nsNone.0 as u32)?;
```

Will close this one out, but please do confirm that works for you.

**Comment by JeromySt** [comment]
Thanks!  I'll look into it!  Me trying to be too smart.

**Comment by JeromySt** [comment]
Seems to have worked!  Thank you!
