### ISSUE TITLE
[QUESTION] DIA SDK fails to parse static libraries PDBs

### ISSUE THREAD

**Issue by dzonerzy** [microsoft/dia-rs#26]
This issue is not strictly related to dia-rs itself but rather to the DIA2 SDK, I've tried compiling a simple project (static library) using Visual Studio 2022 for some reason the resulting PDB seems "empty" to the DIA SDK, not even Dia2Dump utility is able to extract any meaningful information, that said once the PDB is opened with a text editor I can clearly see that many information are there, like the compiled source code, the compiland (object file) and so on.
Any idea why DIA fails to parse this?

[test.zip](https://github.com/user-attachments/files/17616679/test.zip)

**Comment by riverar** [comment]
This may be a [fastlink](https://devblogs.microsoft.com/cppblog/faster-c-build-cycle-in-vs-15-with-debugfastlink/) or otherwise stripped PDB. Can you try building a full program database?

**Comment by dzonerzy** [comment]
> This may be a [fastlink](https://devblogs.microsoft.com/cppblog/faster-c-build-cycle-in-vs-15-with-debugfastlink/) or otherwise stripped PDB. Can you try building a full program database? (See link.)

Hello I've tried to rebuild a full program database, the PDB remains the same size and Dia2Dump still fail to get any information out of it, to reproduce you could just create and new project (static library) create a single file with few functions and compile it in debug mode (for PDB generation).

**Comment by riverar** [comment]
Yup, that sounds right. Here's a stream dump from llvm-pdbutil:

```
  Stream 0 (   80 bytes): [Old MSF Directory]
            Blocks: [5]
  Stream 1 (   75 bytes): [PDB Stream]
            Blocks: [19]
  Stream 2 (12632 bytes): [TPI Stream]
            Blocks: [11, 7, 8, 9]
  Stream 3 (    0 bytes): [DBI Stream]
            Blocks: []
  Stream 4 ( 7268 bytes): [IPI Stream]
            Blocks: [13, 16]
  Stream 5 (   25 bytes): [Named Stream "/names"]
            Blocks: [3]
  Stream 6 ( 1440 bytes): [TPI Hash]
            Blocks: [10]
  Stream 7 (  612 bytes): [IPI Hash]
            Blocks: [12]
```

It's disappointing to see such obscure errors from DIA.

**Comment by riverar** [comment]
Will close this for now since this appears to be an upstream quirk. Feel free to keep the discussion going.
